{{- if and 
  (eq .Values.workloads.type "deployment") 
  (hasKey .Values "deployment") 
  (or 
    (not (hasKey .Values.deployment "rollout")) 
    (not .Values.deployment.rollout.enabled)
  ) 
}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.app.image }} ## docker image name ..? then values.imagepull.dockerconfigjson ?
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          {{- end }}

          {{- if .Values.externalSecrets.enabled }}
          envFrom:
          {{- range .Values.externalSecrets.items }}
            - secretRef:
                name: {{ .name }}
          {{- end }}
          {{- end }}
          
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: 80
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: 80
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
          {{- end }}
          {{- if .Values.secrets.useKeyVault }}
          env:
            - name: VAULT_KV_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.k8sSecretName }}
                  key: someSecretKey
          {{- end }}
{{- end }}